### ISSUE TITLE
Macro for identifying work vs personal email addresses

### ISSUE THREAD

**Issue by Stephen986** [sutrolabs/dbt_census_utils#3]
There should be a macro to check if an e-mail address is from a personal account.  We could set the list of personal e-mails at the top of the macro, but it would probably be better to make a seed file of personal e-mails.  I've attached a list we could use

Macro would look something like this:
{% macro is_personal_email(email_address) %}

{% endmacro %}

Acceptance Criteria:
-Macro returns true if an e-mail address is personal based on the email domain (we can use the extract email domain macro for this).
-Macro returns false if an e-mail address is not personal.
-Macro works on Snowflake, Redshift, and BigQuery.

**Comment by 8WlHSebsMM4Z71kjkvD2CAWSP7qyoVEA4ow6GLw** [comment]
@Stephen986 I think if we create a seed file for free domain provider, then anyone who wants to use our project will have to do a dbt seed before using our macro. I think in any of the projects that we have gone thru, we are not using a database object to run the macro. I think maybe we should keep it in separate macro file itself which returns the list.

**Comment by 7mOatpfIPk6fXjlHH925mn3KecVmtlxoNDCVUpP** [comment]
@amittiwari1979 I discussed this with you and then Jeff @ Census yesterday.  Here's the recap:

1. Requiring people to use 'dbt seed' is fine.  We'll just add that to the documentation as something you have to do after dbt deps.
2. Jeff's preference is that the seed files get built in the user's regular seed file directory.  We'll have to test what happens when a package doesn't specify where the seed files go!  If they're going in the regular seed file directory, I think the files themselves should be prefaced with census_ so it's easy to distinguish them.

**Comment by 7mOatpfIPk6fXjlHH925mn3KecVmtlxoNDCVUpP** [comment]
@amittiwari1979 this macro gets the following error in Snowflake:
Database Error in model test_is_personal_email (models/test_is_personal_email.sql)
16:29:19    001003 (42000): SQL compilation error:
16:29:19    syntax error line 10 at position 99 unexpected 'unnest'.
16:29:19    syntax error line 10 at position 105 unexpected '('.
16:29:19    compiled Code at target/run/census_utils_integration_tests/models/test_is_personal_email.sql

**Comment by 7mOatpfIPk6fXjlHH925mn3KecVmtlxoNDCVUpP** [comment]
Also, is there a reason you're doing an array_agg and then a get_single_value for this macro rather than doing         
 dbt_utils.get_column_values(table=ref('free_email_providers'), column='email_domains')?  That seems to get the same results with less code.

**Comment by 8WlHSebsMM4Z71kjkvD2CAWSP7qyoVEA4ow6GLw** [comment]
> r

@Stephen986 Yeah, the macro is working same with lesser code. I have updated it in Parse GA4 Client Id PR.
