### ISSUE TITLE
Macro for extracting e-mail domains

### ISSUE THREAD

**Issue by Stephen986** [sutrolabs/dbt_census_utils#4]
A very useful macro is one that easily extracts the domain from an e-mail address, so that you can note which people signing up for your product are coworkers.  Here's a simple way to do it:

{% macro extract_email_domain(email_address) %}

{# This is the SQL to extract email domain in the Snowflake SQL: https://docs.snowflake.com/en/sql-reference/functions/regexp_substr #}

    regexp_substr(lower({{ emai_addressl }}), '@(.*)', 1, 1, 'e',1)

{# This is the SQL to extract email domain in BigQuery SQL, which has 2 less parameters: https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#regexp_substr #}

    regexp_substr(lower({{ emai_addressl }}), '@(.*)', 1, 1)

{# Need SQL to extract email domain in Redshift SQL #}

{% endmacro %}

Note: this doesn't currently check for improperly formatted emails, like periods at the end of the domain or whitespaces.

Acceptance Criteria:
-Extract e-mail domain from e-mail addresses.
-Handle improperly formatted e-mails.
-Macro should work in Snowflake, BigQuery, and Redshift.

**Comment by 8WlHSebsMM4Z71kjkvD2CAWSP7qyoVEA4ow6GLw** [comment]
@Stephen986 I will start working on this.

**Comment by 8WlHSebsMM4Z71kjkvD2CAWSP7qyoVEA4ow6GLw** [comment]
Adding list of email domains as reference for any use in project
https://gist.github.com/ammarshah/f5c2624d767f91a7cbdc4e54db8dd0bf
https://disposable.github.io/disposable-email-domains/domains.txt
