### ISSUE TITLE
[Suggestion] Use a subquery to get country codes instead of generating a massive case statement

### ISSUE THREAD

**Issue by joellabes** [sutrolabs/dbt_census_utils#41]
### Describe the issue

https://github.com/sutrolabs/dbt_census_utils/blob/main/macros/get_country_code.sql

Having a 200-line case statement feels pretty icky! Instead, could you do a subquery along these lines? 
```
select 
user_id, 
{{ dbt_census_utils.get_country_code('country_name') }}
from {{ ref('whatever') }}
```

```
select 
user_id,
(select country_code from {{ ref('country_codes') }} where country_name = lower(country_name))
from {{ ref('wherever') }}
```

### Expected behavior

Subquery above

### dbt Project configurations

N/A

### Package versions

Have just eyeballed this, haven't used it in prod

### What database are you using dbt with?

snowflake

### dbt Version

1.5.x

### Are you interested in contributing this feature?

- [ ] Yes.
- [X] No.

**Comment by Stephen986** [comment]
Thanks for the suggestion @joellabes !  To clarify the models each field would come from, I think it would be:

select 
user_id,
(select cc.country_code from {{ ref('country_codes') }} cc where cc.country_name = lower(w.country_name))
from {{ ref('wherever') }} w

We'll try this out and see if it works with prettier compiled code!

**Comment by Stephen986** [comment]
This is fixed now!  We also improved the compiled code of 2 of the other macros with similar methods.
