### ISSUE TITLE
Macro for country name to country code

### ISSUE THREAD

**Issue by Stephen986** [sutrolabs/dbt_census_utils#6]
When sending geographic data to a destination, it's important that all of the country info be consistent and what the destination expects.  If the destination requires country code, or if your DW has a mix of country names and country codes, it's important to convert all of the country names into codes.  We can accomplish this with a seed file mapping names to codes (the same seed can also help with the reverse transformation).

Acceptance Criteria:
-The macro checks for country names, and if it finds a match, converts them to codes.  Everything else is left as is (this way, if it's already a code it will stay that way).
-The macro lowercases country names so that capitalization doesn't affect whether it finds a match.  The country code that is output should be uppercase though.
-If possible, the macro should check for any countries that have been renamed in the past 50 years, ie Burma/Myanmar.  This would be handled by having multiple rows for them in the seed file.

**Comment by 8WlHSebsMM4Z71kjkvD2CAWSP7qyoVEA4ow6GLw** [comment]
downloading the csv from this location.
https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes/blob/master/all/all.csv
